# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'max_hz_set_to_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(201, 252)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_set = QtWidgets.QPushButton(self.centralwidget)
        self.button_set.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.button_set.setObjectName("button_set")
        self.spinB_set = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinB_set.setGeometry(QtCore.QRect(70, 20, 51, 22))
        self.spinB_set.setObjectName("spinB_set")
        self.spinB_small = QtWidgets.QSpinBox(self.centralwidget)
        self.spinB_small.setGeometry(QtCore.QRect(10, 90, 42, 22))
        self.spinB_small.setProperty("value", 1)
        self.spinB_small.setObjectName("spinB_small")
        self.spinB_large = QtWidgets.QSpinBox(self.centralwidget)
        self.spinB_large.setGeometry(QtCore.QRect(70, 90, 42, 22))
        self.spinB_large.setSingleStep(5)
        self.spinB_large.setProperty("value", 10)
        self.spinB_large.setObjectName("spinB_large")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 47, 14))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 47, 14))
        self.label_2.setObjectName("label_2")
        self.button_quit = QtWidgets.QPushButton(self.centralwidget)
        self.button_quit.setGeometry(QtCore.QRect(130, 50, 61, 51))
        self.button_quit.setObjectName("button_quit")
        self.terminal = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(10, 120, 181, 91))
        self.terminal.setObjectName("terminal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 201, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_set.setText(_translate("MainWindow", "set_To"))
        self.label.setText(_translate("MainWindow", "small"))
        self.label_2.setText(_translate("MainWindow", "large "))
        self.button_quit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
